#!/usr/bin/env bash

if
  [[ -s "/home/nitrous/.rvm/gems/ruby-2.1.5@railstutorial_rails_4_0/environment" ]]
then
  source "/home/nitrous/.rvm/gems/ruby-2.1.5@railstutorial_rails_4_0/environment"
  exec bundle "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/nitrous/.rvm/gems/ruby-2.1.5@railstutorial_rails_4_0/environment'" >&2
  exit 1
fi
