#!/usr/bin/env bash

if
  [[ -s "/home/nitrous/.rvm/gems/ruby-2.1.5/environment" ]]
then
  source "/home/nitrous/.rvm/gems/ruby-2.1.5/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/nitrous/.rvm/gems/ruby-2.1.5/environment'" >&2
  exit 1
fi
